AMQP_URI: !env_var '${AMQP_URI}'
WEB_SERVER_ADDRESS: '0.0.0.0:8000'
YOWSUP_USERNAME: !env_var '${USERNAME}'
YOWSUP_PASSWORD: !env_var '${PASSWORD}'
TOKEN_RESEND_MESSAGES: !env_var '${TOKEN_RESEND_MESSAGES}'
ENDPOINT_RESEND_MESSAGES: !env_var '${ENDPOINT_RESEND_MESSAGES}'
rpc_exchange: 'nameko-rpc'
max_workers: 1
parent_calls_tracked: 10
